name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    strategy:
      matrix:
        tag:
        - OpenSSL_0_9_5a-beta1
        - OpenSSL_0_9_6a-beta2
        - OpenSSL_0_9_6i
        - OpenSSL_0_9_7-beta5
        - OpenSSL_0_9_7i
        - OpenSSL_0_9_8-beta5
        - OpenSSL_0_9_8e
        - OpenSSL_0_9_8n
        - OpenSSL_0_9_8x
        - OpenSSL_1_0_0
        - OpenSSL_1_0_0a
        - OpenSSL_1_0_0k
        - OpenSSL_1_0_1
        - OpenSSL_1_0_1c
        - OpenSSL_1_0_1m
        - OpenSSL_1_0_2-beta1
        - OpenSSL_1_0_2d
        - OpenSSL_1_0_2n
        - OpenSSL_1_1_0-pre2
        - OpenSSL_1_1_0f
        - OpenSSL_1_1_1-pre3
        - OpenSSL_1_1_1d
        - OpenSSL_1_1_1n
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: base-devel mingw-w64-i686-gcc git
        update: false
    - name: build.sh
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW32
        CHERE_INVOKING: 'yes'
      run: ./build.sh ${{ matrix.tag }}
    - name: install.sh
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW32
        CHERE_INVOKING: 'yes'
      run: ./install.sh
    - name: zip
      shell: cmd
      run: 7z a ${{ matrix.tag }}.zip OpenSSL
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.tag }}
        path: ${{ matrix.tag }}.zip
