name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    strategy:
      matrix:
        tag:
        - OpenSSL_1_1_1n
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: base-devel mingw-w64-i686-gcc git
        update: false
    - name: build
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW32
        CHERE_INVOKING: 'yes'
      run: ./build.sh ${{ matrix.tag }}
    - name: build
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW32
        CHERE_INVOKING: 'yes'
      run: ./install.sh
    - name: zip
      shell: cmd
      run: 7z a OpenSSL-${{ matrix.tag }}.zip OpenSSL
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: OpenSSL-${{ matrix.tag }}
        path: OpenSSL-${{ matrix.tag }}.zip
