name: main
on: push
env:
  MSYSTEM: MINGW32
  CHERE_INVOKING: 'yes'
jobs:
  main:
    runs-on: windows-latest
    strategy:
      matrix:
        tag:
        - OpenSSL_1_0_1m
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: base-devel mingw-w64-i686-gcc git
        update: false
    - name: build
      shell: msys2 {0}
      run: |
        gcc -v
        perl -v
        git clone git://git.openssl.org/openssl.git src
        cd src
        git checkout ${{ matrix.tag }}
        ./config --prefix="`pwd`/../OpenSSL" --openssldir=ssl --shared
        sed -i 's,-mno-cygwin,,' Makefile
        sed -i 's,i486,i686,' Makefile
        sed -i 's,0x333,0x400,' Makefile
        make
        cd ..
    - name: zip
      shell: cmd
      run: 7z a -y "${{ matrix.tag }}.zip" OpenSSL
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.tag }}
        path: ${{ matrix.tag }}.zip
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.tag }}.zip
